export default function ErrorRetryThrow() {

  throw new Error('from ErrorRetryThrow');

  return (
    <p>正しく実行されました。</p>
  );
}
